# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-25 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('relative_url', models.CharField(max_length=1024)),
                ('notification_type', models.CharField(choices=[(b'ME', b'Message'), (b'NO', b'Notification'), (b'AL', b'Alert')], default=b'NO', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True)),
                ('is_done', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecretGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecretMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.ManyToManyField(related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secrets.Secret')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecretValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.CharField(max_length=1024)),
                ('encrypted_iv', models.CharField(max_length=1024)),
                ('encrypted_value', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='secrets.Secret')),
            ],
        ),
        migrations.CreateModel(
            name='Trust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrustUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('trust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secrets.Trust')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=1024)),
                ('ip_address', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=100)),
                ('public_key', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_authorized', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trust',
            name='users',
            field=models.ManyToManyField(related_name='trusts', through='secrets.TrustUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secretvalue',
            name='userdevice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secrets.UserDevice'),
        ),
        migrations.AddField(
            model_name='secretgroup',
            name='trust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretgroups', to='secrets.Trust'),
        ),
        migrations.AddField(
            model_name='secretgroup',
            name='users',
            field=models.ManyToManyField(related_name='secretgroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secret',
            name='groups',
            field=models.ManyToManyField(related_name='secrets', to='secrets.SecretGroup'),
        ),
    ]
