# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretvalue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretvalue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 23, 18, 8, 31, 25168, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdevice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
