# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 02:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_auto_20160323_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdevice',
            old_name='device_id',
            new_name='agent',
        ),
        migrations.AlterField(
            model_name='secretgroup',
            name='users',
            field=models.ManyToManyField(related_name='secretgroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
