# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0003_auto_20160330_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdevice',
            old_name='device_name',
            new_name='name',
        ),
    ]
