# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0004_auto_20160402_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secretvalue',
            old_name='value',
            new_name='encrypted_value',
        ),
        migrations.AddField(
            model_name='secretvalue',
            name='encrypted_iv',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretvalue',
            name='encrypted_key',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secretvalue',
            name='secret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='secrets.Secret'),
        ),
    ]
