# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0006_secret_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
    ]
