# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0007_userdevice_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='secretgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
