# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0008_auto_20160406_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretgroup',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secretgroup',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
