# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secrets', '0009_auto_20160411_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('admins', models.ManyToManyField(related_name='admin_trusts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='secret',
            name='groups',
            field=models.ManyToManyField(related_name='secrets', to='secrets.SecretGroup'),
        ),
        migrations.AddField(
            model_name='secretgroup',
            name='trust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secrets.Trust'),
        ),
    ]
