# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secrets', '0010_auto_20160419_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='trust',
            name='admins',
        ),
        migrations.AddField(
            model_name='trustusers',
            name='trust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secrets.Trust'),
        ),
        migrations.AddField(
            model_name='trustusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trust',
            name='users',
            field=models.ManyToManyField(through='secrets.TrustUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
