# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 22:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0011_auto_20160420_2159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrustUsers',
            new_name='TrustUser',
        ),
        migrations.AlterField(
            model_name='trust',
            name='users',
            field=models.ManyToManyField(through='secrets.TrustUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
